export const dimensionEntries = [
  ["Query", "The actual search term entered by the user. When anonymized, this will appear as an empty string."],
  ["URL", "The final destination URL the user lands on after clicking a search or Discover result."],
  ["Country", "The user's location at the time of the query, represented as a 3-letter ISO country code (e.g., 'USA')."],
  ["Search Type", "The search vertical used by the user, such as web, image, video, or news."],
  ["Device", "The type of device used to perform the query: desktop, mobile, or tablet."],
  ["Site URL", "The canonical URL of the property. For domain-level sites, starts with sc-domain:. For URL-prefix sites, it's the full base URL."],
  ["Date", "The specific day the data corresponds to, based on Pacific Time."],
  ["Month", "The month associated with the data, in YYYY-MM format."],
  ["Year", "The year associated with the data, in YYYY format."],
  ["Is Anonymized Query", "Indicates if the query is rare enough to be anonymized. The query field will be empty when true."],
  ["Is Anonymized Discover", "Marks whether Discover data is anonymized due to low visibility, which may also remove URL or country fields."],
  ["Is AMP Top Stories", "Indicates whether the result appeared in the AMP Top Stories carousel."],
  ["Is AMP Blue Link", "Marks whether the result was a standard blue link using AMP."],
  ["Is Job Listing", "Marks if the page is a job listing."],
  ["Is Job Details", "Marks if the page contains detailed job information."],
  ["Is TPF QA", "Flags if the URL appeared in top places Q&A rich results."],
  ["Is TPF FAQ", "Flags if the URL appeared in top places FAQ rich results."],
  ["Is TPF HowTo", "Flags if the URL appeared in top places How-To rich results."],
  ["Is Weblite", "Indicates if the URL was served using Google's Web Light format."],
  ["Is Action", "Indicates if the result included interactive action elements."],
  ["Is Events Listing", "Marks whether the URL displayed a list of events."],
  ["Is Events Details", "Marks whether the URL displayed detailed information for a specific event."],
  ["Is Search Appearance Android App", "Indicates if the page appeared through an Android App search result format."],
  ["Is AMP Story", "Indicates if the page was displayed as an AMP Story."],
  ["Is AMP Image Result", "Marks if the result was an AMP-enhanced image result."],
  ["Is Video", "Marks if the result featured a video element."],
  ["Is Organic Shopping", "Flags whether the page was shown in organic shopping results."],
  ["Is Review Snippet", "Indicates if the page included a review snippet (stars, ratings, etc.)."],
  ["Is Special Announcement", "Flags if the page contained a structured special announcement."],
  ["Is Recipe Feature", "Indicates that the page appeared as a recipe carousel or card."],
  ["Is Recipe Rich Snippet", "Marks whether the page showed a rich snippet for a recipe."],
  ["Is Subscribed Content", "Indicates if the content is available only to subscribers."],
  ["Is Page Experience", "Flags if the page passed core web vitals and other UX metrics."],
  ["Is Practice Problems", "Marks whether the URL showed structured practice problems."],
  ["Is Math Solvers", "Indicates whether the result contained structured math-solving content."],
  ["Is Translated Result", "Flags if Google auto-translated the content for display."],
  ["Is Product Snippets", "Marks whether the result included structured product data."],
  ["Is Merchant Listings", "Indicates if the page appeared in the free merchant listings."]
];
